version: "1.1"
services:
  app:
    build: ./
    links:
      - db
    ports: 
      - "5000:5000"
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: "America/Chicago"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
